---
title: "Marked Down version of EDA_OTU.r"

output:
  pdf_document: default
  html_document: default

---
```{r}
# Setting a Working Directory
setwd("~/Desktop")
```

```{r}
#Loading the Needed Libraries
library(phyloseq)
library("vegan")
```

```{r}
#Importing the Data
std_dta  <- import_biom("f120_r1k.biom") #whole data
m_dta <- data.frame(sample_data(std_dta)) #meta data
OTU_dta <- data.frame(otu_table(std_dta)) #OTU data
t_dta <- data.frame(tax_table(std_dta)) #Taxa data
```

```{r}
#Average OTU data
ave_otu_dta<-matrix(NA,nrow=dim(OTU_dta)[1],ncol=length(unique(m_dta$Pack_ID)))
row.names(ave_otu_dta)<-rownames(OTU_dta)
colnames(ave_otu_dta)<-unique(m_dta$Pack_ID)
for (i in unique(m_dta$Pack_ID)){
  temp_id<-rownames(m_dta[m_dta$Pack_ID%in%i,])
  ave_otu_dta[,i]<-rowMeans(OTU_dta[,temp_id])
}
```


#Average values of the columns(sample IDs) in the OTU data
otu_matrix<-data.matrix(ave_otu_dta)
colMeans(otu_matrix)
colMins(otu_matrix)
colMaxs(otu_matrix) 


```{r}
#EDA (Tentative - Rarecurve/Diversity,Clustering, PCA)
otu_dta <- round(as.matrix(ave_otu_dta))
rarecurve(otu_dta)
diversity(otu_dta, index="shannon")
diversity(otu_dta, index="simpson")
```

```{r}
#Clustering
hc_ind <- hclust(dist(ave_otu_dta))
plot(hc_ind)
```

```{r}
#PCA
pca <- prcomp(dist(ave_otu_dta))
summary(pca)
biplot(pca)
```
